# Generated by Django 4.2.3 on 2023-08-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('responsified_image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50)),
                ('hide', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('slug', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('tag', models.CharField(max_length=50)),
                ('tag_color', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=9999)),
                ('on_top_product', models.BooleanField(default=False)),
                ('hide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductImagery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.product')),
            ],
            options={
                'verbose_name': 'Imagery',
                'verbose_name_plural': 'Imageries',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, to='Store.size'),
        ),
        migrations.CreateModel(
            name='Pending_Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivered', models.BooleanField(blank=True, default=False)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('payment', models.CharField(blank=True, max_length=30)),
                ('delivery', models.CharField(blank=True, max_length=30)),
                ('cart', models.TextField(blank=True, null=True)),
                ('placement_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.customer')),
            ],
            options={
                'verbose_name': 'Order (Pending)',
                'verbose_name_plural': 'Orders (Pending)',
            },
        ),
        migrations.CreateModel(
            name='Delivered_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.TextField(blank=True, null=True)),
                ('payment', models.CharField(blank=True, max_length=30)),
                ('delivery', models.CharField(blank=True, max_length=30)),
                ('ordered_date', models.CharField(max_length=20)),
                ('delivered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.customer')),
            ],
            options={
                'verbose_name': 'Order (Delivered)',
                'verbose_name_plural': 'Orders (Delivered)',
            },
        ),
    ]
