# Generated by Django 4.2.3 on 2023-08-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[], max_length=13, null=True),
        ),
    ]
