# Generated by Django 4.2.2 on 2023-06-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='raw_slug',
            field=models.CharField(default='r', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prodimages',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
