# Generated by Django 4.2.3 on 2023-08-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('For kids', 'For kids'), ('Man', 'Man')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='hide',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='on_top_product',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag_color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
