# Generated by Django 4.2.2 on 2023-06-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_product_raw_slug_alter_prodimages_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('accessories', 'accessories'), ('prints', 'prints'), ('modest wear', 'modest wear'), ('unstitched', 'unstitched'), ('ready to wear', 'ready to wear')], max_length=13),
        ),
    ]
