# Generated by Django 4.2.2 on 2023-06-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_product_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='onTopProduct',
            new_name='on_top_product',
        ),
    ]
