# Generated by Django 4.2.2 on 2023-06-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_product_desc'),
        ('Store', '0004_rename_ontopproduct_product_on_top_product'),
    ]

    operations = [
    ]
