# Generated by Django 4.2.2 on 2023-06-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_merge_20230620_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=30)),
                ('delivery', models.CharField(max_length=30)),
                ('cart', models.JSONField()),
            ],
        ),
    ]
