# Generated by Django 4.2.2 on 2023-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_order_cart_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='html_id',
            field=models.CharField(default='Order', max_length=255),
        ),
    ]
