# Generated by Django 4.2.2 on 2023-06-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_order_html_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodimages',
            name='html_id',
            field=models.CharField(default='Images', max_length=255),
        ),
    ]
