# Generated by Django 4.2.2 on 2023-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_prodimages_html_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='navslider',
            name='html_id',
            field=models.CharField(default='Navbar', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='html_id',
            field=models.CharField(default='Products', max_length=255),
        ),
    ]
