# Generated by Django 4.2.2 on 2023-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_navslider_html_id_product_html_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='html_id',
            field=models.CharField(default='News', max_length=255),
        ),
    ]
