# Generated by Django 4.2.2 on 2023-06-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_news_html_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navslider',
            old_name='url',
            new_name='name',
        ),
    ]
