# Generated by Django 4.2.2 on 2023-06-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0013_rename_url_navslider_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news',
            new_name='name',
        ),
    ]
