# Generated by Django 4.2.2 on 2023-06-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_rename_news_news_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navslider',
            name='html_id',
            field=models.CharField(blank=True, default='Navbar', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='html_id',
            field=models.CharField(blank=True, default='News', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='html_id',
            field=models.CharField(blank=True, default='Order', max_length=255),
        ),
        migrations.AlterField(
            model_name='prodimages',
            name='html_id',
            field=models.CharField(blank=True, default='Images', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('accessories', 'accessories'), ('prints', 'prints'), ('modest wear', 'modest wear'), ('unstitched', 'unstitched'), ('ready to see', 'ready to see')], max_length=13),
        ),
        migrations.AlterField(
            model_name='product',
            name='html_id',
            field=models.CharField(blank=True, default='Products', max_length=255),
        ),
    ]
