# Generated by Django 4.2.2 on 2023-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_alter_navslider_html_id_alter_news_html_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
