# Generated by Django 4.2.2 on 2023-07-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
