# Generated by Django 4.2.2 on 2023-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_news_hide_product_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
