# Generated by Django 4.2.3 on 2023-07-27 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_alter_category_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delivered_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.TextField(blank=True, null=True)),
                ('payment', models.CharField(blank=True, max_length=30)),
                ('delivery', models.CharField(blank=True, max_length=30)),
                ('ordered_date', models.CharField(max_length=20)),
                ('delivered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.customer')),
            ],
            options={
                'verbose_name': 'Delivered_Order',
                'verbose_name_plural': 'Delivered_Orders',
            },
        ),
        migrations.CreateModel(
            name='Pending_Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivered', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('firstname', models.CharField(blank=True, max_length=50)),
                ('lastname', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('payment', models.CharField(blank=True, max_length=30)),
                ('delivery', models.CharField(blank=True, max_length=30)),
                ('cart', models.TextField(blank=True, null=True)),
                ('html_id', models.CharField(blank=True, default='Order', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.customer')),
            ],
            options={
                'verbose_name': 'Pending_Order',
                'verbose_name_plural': 'Pending_Orders',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(choices=[('accessories', 'accessories'), ('prints', 'prints'), ('modest-wear', 'modest-wear'), ('unstitched', 'unstitched'), ('ready to see', 'ready to see')], max_length=13),
        ),
    ]
