# Generated by Django 4.2.3 on 2023-07-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0019_customer_delivered_order_pending_order_delete_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.customer'),
        ),
    ]
