# Generated by Django 4.2.3 on 2023-07-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0020_alter_pending_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_order',
            name='delivered',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
