# Generated by Django 4.2.3 on 2023-07-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_alter_pending_order_delivered'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivered_order',
            options={'verbose_name': 'Order (Delivered)', 'verbose_name_plural': 'Orders (Delivered)'},
        ),
        migrations.AlterModelOptions(
            name='pending_order',
            options={'verbose_name': 'Order (Pending)', 'verbose_name_plural': 'Orders (Pending)'},
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=10)),
                ('belongs_to', models.ManyToManyField(to='Store.product')),
            ],
            options={
                'verbose_name': 'Product Sizes',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=10)),
                ('belongs_to', models.ManyToManyField(to='Store.product')),
            ],
            options={
                'verbose_name': 'Product Colors',
            },
        ),
    ]
