# Generated by Django 4.2.3 on 2023-07-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_alter_delivered_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Product Color', 'verbose_name_plural': 'Product Colors'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Product Size', 'verbose_name_plural': 'Product Sizes'},
        ),
        migrations.RemoveField(
            model_name='color',
            name='belongs_to',
        ),
        migrations.RemoveField(
            model_name='size',
            name='belongs_to',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='Store.color'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='Store.size'),
        ),
    ]
